name: Page Replace
on:
  push:
    branches: 
      - gh-pages
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # https://github.com/jacobtomlinson/gha-find-replace
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
         find: <!--[\s\S]*?-->
         replace: ""
         include: "docs/*.md"
         
      - name: Deploy
        # https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # default: public
